// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletApp.DataAccess.Data;

#nullable disable

namespace WalletApp.DataAccess.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    partial class WalletAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.DataAccess.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AuthorizedUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateDisplay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f705611e-f346-4f5f-a4a8-ff09232b37d6"),
                            Amount = 20m,
                            Date = new DateTime(2024, 11, 14, 12, 48, 23, 757, DateTimeKind.Utc).AddTicks(2151),
                            DateDisplay = "2024-11-19 12:48:23",
                            Description = "Desc about IKEA",
                            Status = "Completed",
                            TransactionName = "IKEA",
                            Type = "Payment",
                            UserId = new Guid("5d5a34ff-1429-44e6-b355-af88f6917149")
                        },
                        new
                        {
                            Id = new Guid("85a54a2c-72f6-47ec-9e4d-1c76132dcdfd"),
                            Amount = 50m,
                            Date = new DateTime(2024, 11, 17, 12, 48, 23, 757, DateTimeKind.Utc).AddTicks(2165),
                            DateDisplay = "2024-11-19 12:48:23",
                            Description = "Desc about Target",
                            Status = "Completed",
                            TransactionName = "Target",
                            Type = "Credit",
                            UserId = new Guid("5d5a34ff-1429-44e6-b355-af88f6917149")
                        },
                        new
                        {
                            Id = new Guid("9a2c1b2f-ef6c-428c-b7a8-ea596853edb4"),
                            Amount = 100m,
                            Date = new DateTime(2024, 11, 18, 12, 48, 23, 757, DateTimeKind.Utc).AddTicks(2172),
                            DateDisplay = "2024-11-19 12:48:23",
                            Description = "Refueling the car",
                            Status = "Pending",
                            TransactionName = "Fuel",
                            Type = "Payment",
                            UserId = new Guid("5d5a34ff-1429-44e6-b355-af88f6917149")
                        });
                });

            modelBuilder.Entity("WalletApp.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d5a34ff-1429-44e6-b355-af88f6917149"),
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("WalletApp.DataAccess.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CardLimit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d283f96-430a-49a7-adf9-7fcb0c275152"),
                            Balance = 100m,
                            CardLimit = 1500m,
                            UserId = new Guid("5d5a34ff-1429-44e6-b355-af88f6917149")
                        });
                });

            modelBuilder.Entity("WalletApp.DataAccess.Entities.Wallet", b =>
                {
                    b.HasOne("WalletApp.DataAccess.Entities.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("WalletApp.DataAccess.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WalletApp.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
